### ISSUE TITLE
如果滚动到列表中间，然后删除列表的前 100 个数据，再向上滚动后发现列表顶部出现一段空白

### ISSUE THREAD

**Issue by Stardusten** [keno-lee/vue-virt-list#13]
![image](https://github.com/keno-lee/vue-virt-list/assets/38722307/0ef6a276-c963-4df5-83c4-8e53f8a2a22c)

![image](https://github.com/keno-lee/vue-virt-list/assets/38722307/0c1aad02-9bd2-4e2b-ad31-4a0fe172f515)

复现代码：

```ts
<template>
  <div class="main">
    <VirtList
        :list="list"
        ref="virtListRef"
        itemKey="id"
        :minSize="20"
    >
      <template #default="{ itemData, index }">
        <div>{{ itemData.text }}</div>
      </template>
    </VirtList>
  </div>
</template>

<script lang="ts">
import { VirtList } from 'vue-virt-list';

export default {
  name: 'DemoFixed',
  components: {
    VirtList,
  },
  data() {
    return {
      list: [] as any[],

      reactiveData: {
        renderBegin: 0,
        renderEnd: 0,
      },
    };
  },
  mounted() {
    this.reactiveData = (this.$refs.virtListRef as any).reactiveData;
    this.list = [];
    for (let i = 0; i < 1000; i ++) {
      this.list.push({ id: i, text: "block_" + i })
    }
    setTimeout(() => {
      this.list.splice(0, 200);
    }, 5000);
  },
};
</script>

<style>
.demo-fixed {
  width: 100%;
  height: 500px;
  overflow: hidden;
}
</style>
```

**Comment by Stardusten** [comment]
似乎如果设置 minSize=40，并且使用 ref 而不是 shallowRef 就不会有问题。

**Comment by Stardusten** [comment]
问题似乎和 itemSize 的计算误差有关，在 list 较小或者每次删除较少元素时，不会有什么问题。但是如果列表很大（比如 10000 个元素），每次删除很多元素（比如 100 个），并且指定的 minSize 并不太精确时会产生问题。

**Comment by Stardusten** [comment]
尝试了一下，在 VirtList.tsx 734 行做如下修改能够解决问题：

```ts
watch(
    () => props.list.length,
    () => {
      // 如果数据为空，那么就重置
      if (props.list.length <= 0) {
        reset();
        return;
      }

      // console.log("total size before=", getTotalSize(), getVirtualSize2beginInView())
      // [require] 因为list长度变化，所以总高度有变化
      calcListTotalSize();
      // console.log("total size after=", getTotalSize(), getVirtualSize2beginInView())
      // [require] 因为list长度变化，所以重新计算起始结束位置
      updateRange(reactiveData.inViewBegin);
      // [require] 起始位置可能不变，但列表元素发生变化，所以强制渲染一次
      forceUpdate();
      requestIdleCallback(() => {
        updateTotalVirtualSize(); // 修改了这里
      });
    },
    {
      immediate: true,
    },
  );
```

但是这样改以后仍有以下两个问题：

- 滚动位置保持不变，导致列表整体往上 / 往下挪动
- 列表较长时会闪烁一下

**Comment by keno-lee** [comment]
> 尝试了一下，在 VirtList.tsx 734 行做如下修改能够解决问题：
> 
> ```ts
> watch(
>     () => props.list.length,
>     () => {
>       // 如果数据为空，那么就重置
>       if (props.list.length <= 0) {
>         reset();
>         return;
>       }
> 
>       // [require] 因为list长度变化，所以总高度有变化
>       calcListTotalSize();
>       // [require] 因为list长度变化，所以重新计算起始结束位置
>       updateRange(reactiveData.inViewBegin);
>       // [require] 起始位置可能不变，但列表元素发生变化，所以强制渲染一次
>       forceUpdate();
>       requestIdleCallback(() => {
>         updateTotalVirtualSize(); // 修改了这里
>       });
>     },
>     {
>       immediate: true,
>     },
>   );
> ```
> 
> 但是这样改以后仍有以下两个问题：
> 
> - 滚动位置保持不变，导致列表整体往上 / 往下挪动
> - 列表较长时会闪烁一下

收到，大佬！我试试看怎么解决。这次做的虚拟列表兼容的场景太多了，我以为都全了，原来还有这么多，感谢大家反馈，我会尽快兼容😉

**Comment by keno-lee** [comment]
> 似乎如果设置 minSize=40，并且使用 ref 而不是 shallowRef 就不会有问题。

你好，如果是需要删除大量数据建议使用 deletedList2Top 该方法。这个方法在分页demo中有用到
<img width="570" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/35287326/ec0714ea-ae1f-4d16-ac58-11a308cd7c51">

**Comment by keno-lee** [comment]
> > 尝试了一下，在 VirtList.tsx 734 行做如下修改能够解决问题：
> > ```ts
> > watch(
> >     () => props.list.length,
> >     () => {
> >       // 如果数据为空，那么就重置
> >       if (props.list.length <= 0) {
> >         reset();
> >         return;
> >       }
> > 
> >       // [require] 因为list长度变化，所以总高度有变化
> >       calcListTotalSize();
> >       // [require] 因为list长度变化，所以重新计算起始结束位置
> >       updateRange(reactiveData.inViewBegin);
> >       // [require] 起始位置可能不变，但列表元素发生变化，所以强制渲染一次
> >       forceUpdate();
> >       requestIdleCallback(() => {
> >         updateTotalVirtualSize(); // 修改了这里
> >       });
> >     },
> >     {
> >       immediate: true,
> >     },
> >   );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是这样改以后仍有以下两个问题：
> > 
> > * 滚动位置保持不变，导致列表整体往上 / 往下挪动
> > * 列表较长时会闪烁一下
> 
> 收到，大佬！我试试看怎么解决。这次做的虚拟列表兼容的场景太多了，我以为都全了，原来还有这么多，感谢大家反馈，我会尽快兼容😉

这个建议也挺好的，会采纳进去。

**Comment by keno-lee** [comment]
> > > 尝试了一下，在 VirtList.tsx 734 行做如下修改能够解决问题：
> > > ```ts
> > > watch(
> > >     () => props.list.length,
> > >     () => {
> > >       // 如果数据为空，那么就重置
> > >       if (props.list.length <= 0) {
> > >         reset();
> > >         return;
> > >       }
> > > 
> > >       // [require] 因为list长度变化，所以总高度有变化
> > >       calcListTotalSize();
> > >       // [require] 因为list长度变化，所以重新计算起始结束位置
> > >       updateRange(reactiveData.inViewBegin);
> > >       // [require] 起始位置可能不变，但列表元素发生变化，所以强制渲染一次
> > >       forceUpdate();
> > >       requestIdleCallback(() => {
> > >         updateTotalVirtualSize(); // 修改了这里
> > >       });
> > >     },
> > >     {
> > >       immediate: true,
> > >     },
> > >   );
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 但是这样改以后仍有以下两个问题：
> > > 
> > > * 滚动位置保持不变，导致列表整体往上 / 往下挪动
> > > * 列表较长时会闪烁一下
> > 
> > 
> > 收到，大佬！我试试看怎么解决。这次做的虚拟列表兼容的场景太多了，我以为都全了，原来还有这么多，感谢大家反馈，我会尽快兼容😉
> 
> 这个建议也挺好的，会采纳进去。

我测试过其他一些虚拟列表都会有闪烁情况，因为长度减少导致滚动条变化，会触发滚动。后面会上线一个虚拟滚动条，能彻底解决该问题

**Comment by keno-lee** [comment]
v1.0.7 已解决
