### ISSUE TITLE
reset或list置空时 没有清空renderlist 导致列表有残留数据 必须调用forceupdate 才能刷新

### ISSUE THREAD

**Issue by CSNight** [keno-lee/vue-virt-list#25]
reset或list置空时 没有清空renderlist 导致列表有残留数据 必须调用forceupdate 才能刷新
![image](https://github.com/keno-lee/vue-virt-list/assets/34117303/272ed337-7f06-4221-9572-ba45fcc2097d)

**Comment by CSNight** [comment]
![image](https://github.com/keno-lee/vue-virt-list/assets/34117303/88bb1d8f-8fcc-47b7-a0aa-36eee63cea99)

**Comment by keno-lee** [comment]
> ![image](https://private-user-images.githubusercontent.com/34117303/322686528-88bb1d8f-8fcc-47b7-a0aa-36eee63cea99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTI0NzgsIm5iZiI6MTcxMzI1MjE3OCwicGF0aCI6Ii8zNDExNzMwMy8zMjI2ODY1MjgtODhiYjFkOGYtOGZjYy00N2I3LWEwYWEtMzZlZWU2M2NlYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMzBhMzk3NGE3OWE3YzdkZTVkMGVjOTEyNzNmZDk1NmYyYzFmMDVmYzg5ZTliMmQxYWZiZWU5YTAwZGRjYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cRsmoEnsh8Ebe3T6auochXHMru3RN9sj0mpLBQ8EQ7c)

确实有问题，感谢反馈。今晚会发版。暂时可以手动调用一下forceUpdate。发版完成后这里回复你。

**Comment by keno-lee** [comment]
> ![image](https://private-user-images.githubusercontent.com/34117303/322686528-88bb1d8f-8fcc-47b7-a0aa-36eee63cea99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjY0MjksIm5iZiI6MTcxMzI2NjEyOSwicGF0aCI6Ii8zNDExNzMwMy8zMjI2ODY1MjgtODhiYjFkOGYtOGZjYy00N2I3LWEwYWEtMzZlZWU2M2NlYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDExMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YWM1Yzk5YzgwMzkyZGRkZjA3ZDRmZTI3NzY4NTM5NWM0ZmRkODA2OTYxMWU3Y2Q3YjYwZWQyMjU4OThmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMgko-yeCeMMUvcqD-Z-AZ7k4gFlnLgLAUl6yDwcplU)

已修复，感谢反馈。版本：vue-virt-list@1.0.9
