### ISSUE TITLE
安卓设备兼容问题

### ISSUE THREAD

**Issue by Tangjuyi** [keno-lee/vue-virt-list#32]
ResizeObserver 方法 安卓7,8  兼容有问题 "ReferenceError: ResizeObserver is not defined",

**Comment by keno-lee** [comment]
> ResizeObserver 方法 安卓7,8 兼容有问题 "ReferenceError: ResizeObserver is not defined",

需要自己引入polyfill即可 https://www.npmjs.com/package/resize-observer-polyfill
