### ISSUE TITLE
gride 布局 怎么用 一行两个item的样式

### ISSUE THREAD

**Issue by yhyeye** [keno-lee/vue-virt-list#36]
gride 布局 怎么用？ 一行里面有两个item这种布局，应该怎么使用这个虚拟滚动？？

**Comment by keno-lee** [comment]
@yhyeye 这个可以通过操作list内容结构进行设置。比如：const list = [{ 'item1', "item2" }, { 'item3', 'item4' }];

**Comment by keno-lee** [comment]
@yhyeye 已在开发一个开箱即用的grid组件，可以持续关注下~。开发完毕知会你，感谢建议。
