### ISSUE TITLE
绑定的数据源发生变化之后，视图不会改变

### ISSUE THREAD

**Issue by Jerry930326** [keno-lee/vue-virt-list#41]
视图show过之后，数据源在发生增删的情况下，视图的数据不会变化，需要手动调用一次forceUpdate方法

**Comment by keno-lee** [comment]
如果你使用了shallowRef，那么就需要手动更新，是符合逻辑的
https://keno-lee.github.io/vue-virt-list/zh/examples/huge-data

**Comment by Jerry930326** [comment]
> 如果你使用了shallowRef，那么就需要手动更新，是符合逻辑的 https://keno-lee.github.io/vue-virt-list/zh/examples/huge-data

没有使用shallowRef，使用的ref

**Comment by keno-lee** [comment]
list.length是否发生变化？你可以加我微信
