### ISSUE TITLE
vue-router 的 keep-alive 的页面使用了vue-virt-list，会出现很多状况。

### ISSUE THREAD

**Issue by lisiyizu** [keno-lee/vue-virt-list#44]
如果用了vue-virt-list 的列表页面有设置 keep-alive 的情况，列表项点击详情，再返回列表页面，会出现以下三个问题：
1. 页面显示不出数据，显示空白
2. 滚动条显示的数据项位置不对
3. 发起了底部加载的请求，有时候会发多个请求。

**Comment by keno-lee** [comment]
感谢反馈，之前没考虑过组件销毁再挂载的情况。会尽快完善

**Comment by lisiyizu** [comment]
> 感谢反馈，之前没考虑过组件销毁再挂载的情况。会尽快完善

期待大佬，尽快解决。

**Comment by lisiyizu** [comment]
> 感谢反馈，之前没考虑过组件销毁再挂载的情况。会尽快完善

我做了一个复现Demo：https://github.com/lisiyizu/vue-virt-list-demo
