### ISSUE TITLE
Bug：向下滚动时，会出现无限滚动直到底部；向上滚动时，滚动过长

### ISSUE THREAD

**Issue by lijiongquan** [keno-lee/vue-virt-list#45]
问题1：向下滚动时，会出现无限滚动直到底部
问题2：向上滚动时，滚动过快，比如：我在第100行，向上滑动一小下滚轮，直接就跳到90行左右

下方为复现代码，引入element-plus组件即可

**Comment by keno-lee** [comment]
大概知道原因了，你的item minsize实际高度应该是小于20的。
<img width="1282" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/35287326/c836de88-0b66-4722-9ed8-d60e42c6fa26">

**Comment by keno-lee** [comment]
<img width="434" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/35287326/7aa028ad-3783-4aeb-993f-16cc41a68fcf">
<img width="410" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/35287326/5f70368a-3a47-4d07-965e-45f1b8c6f929">
数据没有id

**Comment by lijiongquan** [comment]
确实是没有id引起的，使用问题
