### ISSUE TITLE
在部分安卓手机企业微信内滑动卡顿

### ISSUE THREAD

**Issue by keven1ove** [keno-lee/vue-virt-list#48]
UA: Mozilla/5.0 (Linux; Android 13; Mi 10 Pro Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.86 MQQBrowser/6.2 TBS/047001 Mobile Safari/537.36 wxwork/4.1.27 MicroMessenger/7.0.1 NetType/WIFI Language/zh Lang/zh ColorScheme/Light

上下滚动滑动，和这个比较相似
https://github.com/youzan/vant/issues/6032

**Comment by keno-lee** [comment]
resolved: https://github.com/keno-lee/vue-virt-list/pull/47
