### ISSUE TITLE
网格模式下，改变窗口大小可能导致显示为空

### ISSUE THREAD

**Issue by LoYoi-i** [keno-lee/vue-virt-list#49]
首先有一个很长的数组500.。。。

窗口大小实时计算每一行的个数，然后将滚动条滑动到下方，然后改变窗口大小

![image](https://github.com/user-attachments/assets/033da501-0220-48ef-b18c-8c099fbec0ac)

z这个是最开始，注意滚动条位置

![image](https://github.com/user-attachments/assets/ea859031-cf27-4202-aebe-32836fbf9e40)

改变大小后，这个时候还是正常的，如果再对窗口大小改变，都会导致显示为空

![image](https://github.com/user-attachments/assets/e7698505-2b72-4de0-b3f2-9b8d823b2156)

但是滚动一下鼠标，就会显示画面，然后如果再继续调整窗口大小，还是会导致显示为空

我看了源代码，不太会jsx，所以暂时不能参与修改，希望大佬能够修复！

**Comment by keno-lee** [comment]
收到！安排～急的话可以加我好友

**Comment by keno-lee** [comment]
重新梳理了你的场景，这个场景需要业务自行定制处理了。处理办法也简单，就是gridItems发生变化的时候，调用forceUpdate。如果你想要保持当前卡片的位置，你需要改成调用 scrollToIndex

**Comment by LoYoi-i** [comment]
> 重新梳理了你的场景，这个场景需要业务自行定制处理了。处理办法也简单，就是gridItems发生变化的时候，调用forceUpdate。如果你想要保持当前卡片的位置，你需要改成调用 scrollToIndex

我给你反馈，就是希望在组件里面自动更新，行个数变化应该能监听到吧，手动更新我知道，我反馈里面也说了，要重新滚动一下鼠标，就会显示正常

**Comment by keno-lee** [comment]
> > 重新梳理了你的场景，这个场景需要业务自行定制处理了。处理办法也简单，就是gridItems发生变化的时候，调用forceUpdate。如果你想要保持当前卡片的位置，你需要改成调用 scrollToIndex
> 
> 我给你反馈，就是希望在组件里面自动更新，行个数变化应该能监听到吧，手动更新我知道，我反馈里面也说了，要重新滚动一下鼠标，就会显示正常

哥们看看符合你的预期不，版本：v1.4.2 ，代码变动内容：https://github.com/keno-lee/vue-virt-list/pull/50
