### ISSUE TITLE
ios下拉皮筋效果适配

### ISSUE THREAD

**Issue by Tangjuyi** [keno-lee/vue-virt-list#5]
https://keno-lee.github.io/vue-virt-list/examples/chat/  聊天室demo
 ios 由于下拉皮筋效果，在加载中多下拉几次，滚动位置会一直在顶部

临时解决方案
 document.querySelector(".virt-list__client").style.overflow = "hidden"

**Comment by keno-lee** [comment]
> https://keno-lee.github.io/vue-virt-list/examples/chat/ 聊天室demo ios 由于下拉皮筋效果，在加载中多下拉几次，滚动位置会一直在顶部
> 
> 临时解决方案 document.querySelector(".virt-list__client").style.overflow = "hidden"

收到，试了一下，在IOS的safari和chrome中，确实有这个问题。初步判断为toTop和toBottom的问题，具体原因再详细排查一下

**Comment by keno-lee** [comment]
> https://keno-lee.github.io/vue-virt-list/examples/chat/ 聊天室demo ios 由于下拉皮筋效果，在加载中多下拉几次，滚动位置会一直在顶部
> 
> 临时解决方案 document.querySelector(".virt-list__client").style.overflow = "hidden"

已经在v1.0.2版本中解决该问题，主要原因是ios中resizeOberver兼容性问题。但发现ios浏览器中向上平滑滚动功能仍旧有问题，修复抖动的代码无法生效，原因还在寻找中，ios和safari不愧是现代版本ie。后续有进展我回复你，感谢反馈

以下是发布内容：

修复ios浏览器resizeObserver兼容性问题，（其他浏览器不受影响）
- contentRect 仅在旧版本浏览器中生效，例如ios中（包含safari和chrome），其他浏览器应当使用 contentBoxSize
- Firefox 实现 contentBoxSize 是一个对象, 而其他浏览器是数组

**Comment by Tangjuyi** [comment]
> 聊天室场景更推荐使用：RealList。已在真实IM聊天项目中使用 https://keno-lee.github.io/vue-virt-list/examples/pagination-real/

这个应该不适合聊天室，大多聊天室都是向上翻页，类似微信一样

**Comment by keno-lee** [comment]
> > 聊天室场景更推荐使用：RealList。已在真实IM聊天项目中使用 https://keno-lee.github.io/vue-virt-list/examples/pagination-real/
> 
> 这个应该不适合聊天室，大多聊天室都是向上翻页，类似微信一样

只是demo中，初始的时候没设置成最后一页。如果设置成最后一页就可以了。IM有两种，一个是向上加载更多的时候，内存数据稳定增加。还有一种是上下数据都采取分页模式（减少内存使用量），不管是向上还是向下都是从新拉取数据，这种就可以采用demo中的分页模式

**Comment by Tangjuyi** [comment]
> > > 聊天室场景更推荐使用：RealList。已在真实IM聊天项目中使用https://keno-lee.github.io/vue-virt-list/examples/pagination-real/
> > 
> > 
> > 这个应该不适合聊天室，大部分聊天室都是向上翻页，类似微信一样
> 
> 只是demo中，初始的时候没设置成最后一页。如果设置成最后一页就可以了。IM有两种，一个是向上加载更多的时候，内存稳定数据增加。还有一种是上下数据都采用分页模式（减少内存使用量），无论是向上还是延续都是从新拉取数据，这种就可以采用demo中的分页模式

膜拜大佬
