### ISSUE TITLE
使用grid布局和滚动分页加载的功能在虚拟列表中当快速向下不停滚动时会出现元素抖动问题

### ISSUE THREAD

**Issue by LJL0906** [keno-lee/vue-virt-list#64]
我使用deep修改了部分组件内样式，不确定会不会影响滚动效果，如果复现不了就算了

**Comment by keno-lee** [comment]
> 我使用deep修改了部分组件内样式，不确定会不会影响滚动效果，如果复现不了就算了

好的哥。我试试
