### ISSUE TITLE
设置buffer并不起作用

### ISSUE THREAD

**Issue by JQHee** [keno-lee/vue-virt-list#7]
<img width="1005" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/0016405b-6638-4ea1-abc7-a2acc6ab73f4">

<img width="1541" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/4d39755e-6005-4b43-a6d7-ac8f6e28ba41">

**Comment by keno-lee** [comment]
> <img width="1005" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/0016405b-6638-4ea1-abc7-a2acc6ab73f4">
> 
> <img width="1541" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/4d39755e-6005-4b43-a6d7-ac8f6e28ba41">
> 
> 
要设置一个限定的高度。

**Comment by JQHee** [comment]
<img width="1246" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/a140c8b2-91e3-4e20-a284-fe95a6b873d2">
<img width="1237" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/69391583-80fd-45f1-acf0-490e21146358">

开始直接滑动到底部，再向上滑动的时候，dom越增越多

**Comment by JQHee** [comment]
```
<template>
	<view class="content">
		<view class="buttons-wrapper">
			<view class="to-bottom" @click="toBottomClick">底部</view>
			<view class="to-position" @click="toPositionClick">定位</view>
		</view>
		<view class="virtList-content">
			<VirtList
				class="virtList"
				ref="virtListRef"
				:buffer="5"
				itemKey="id"
				:list="items"
				:minSize="0"
				@toTop="onToTop"
				@toBottom="onToBottom"
				@itemResize="itemResize"
				@scroll="onScroll"
			>
				<template #default="{ itemData, index }">
					<view class="virt-item" :data-index="index">
						<view v-if="itemData.type === 0">{{ index }} - {{ itemData.text }}</view>
						<image v-if="itemData.type === 1" :src="itemData.text" />
					</view>
				</template>
				<template #header v-if="isShowLoading">
					<view style="width: 100%; height: 20px; display: flex; justify-content: center; align-items: center; background-color: chocolate">loading...</view>
				</template>
			</VirtList>
		</view>
	</view>
</template>

<script>
import { VirtList } from 'vue-virt-list';
// 这个稍
export default {
	components: { VirtList },
	data() {
		return {
			items: [],
			isShowLoading: false,
			lastIndex: null
		};
	},
	onLoad() {
		this.virtListRef = this.$refs.virtListRef;
		for (let i = 0; i < 1000; i++) {
			const item = { text: '', id: i, type: 0 };
			item.text = '测试内容';
			if (i % 2 === 0) {
				item.text = '测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容';
			} else if (i % 5 === 0) {
				item.type = 1;
				item.text = 'https://newfile.ofweek.net/fileremote/msg/chat/2023-04/20230419175448321_dl.png';
			}
			this.items.push(item);
		}
		this.$nextTick(() => {
			this.$refs.virtListRef.scrollToBottom();
		});
	},
	methods: {
		async onToTop() {
			console.log('onToTop');
			if (this.isShowLoading) return;
			this.isShowLoading = true;
		},
		async onToBottom() {
			console.log('onToBottom');
		},
		async itemResize() {},
		async onScroll(event) {
			//console.log(event);
			const chatListWrapperDom = document.querySelector('.virtList-content');
			const offsetY = this.$refs.virtListRef && this.$refs.virtListRef.getOffset();
			const targetOffsetY = Math.abs(offsetY) + chatListWrapperDom.clientHeight;

			console.log(targetOffsetY);
			let list = document.querySelectorAll('.virt-item'); // 查找所有view元素
			for (let i = 0; i < list.length; i++) {
				const item = list[i];
				//debugger;
				if (targetOffsetY >= item.offsetTop && targetOffsetY <= item.offsetTop + item.clientHeight) {
					// 取出id
					if (this.lastIndex === item.dataset.index) {
						return;
					}
					this.lastIndex = item.dataset.index;
					console.log('目标元素 item.dataset.index', item.dataset.index);
					console.log('目标元素 item.dataset.offsetTop', item.offsetTop);
					console.log('目标元素 item.dataset.maxOffsetY', item.offsetTop + item.clientHeight);
					break;
				}
			}
		},
		toBottomClick() {
			this.$refs.virtListRef?.scrollToBottom();
		},
		toPositionClick() {
			let timeout = setTimeout(() => {
				this.$refs.virtListRef?.scrollIntoView(50);
				clearTimeout(timeout);
				timeout = null;
			}, 20);
		}
	}
};
</script>

<style lang="scss" scoped>
.content {
	width: 100%;
	height: 100%;
	display: flex;
	flex-direction: column;
	.buttons-wrapper {
		display: flex;
		flex-direction: row;
		height: 8vmin;
	}
	.virtList-content {
		width: 100%;
		height: calc(100vmin - 11.73vmin - 8vmin);
	}
}
</style>

```

**Comment by keno-lee** [comment]
> > <img alt="image" width="1005" src="https://private-user-images.githubusercontent.com/12505317/307729990-0016405b-6638-4ea1-abc7-a2acc6ab73f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjgwNzYsIm5iZiI6MTcwOTAyNzc3NiwicGF0aCI6Ii8xMjUwNTMxNy8zMDc3Mjk5OTAtMDAxNjQwNWItNjYzOC00ZWExLWFiYzctYTJhY2M2YWI3M2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjZkYzE1YzkzMmQ5YTk4NmNlOGNkZGNhYTkyMzYzOGQ5YmY1MmE2NzZiYWEzOTEwMzMzZjJjMzc2ZWJjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lsheFW6xk0dUzv2r3tcaUsZtVNeipOwRvadOgM5y_Fs">
> > <img alt="image" width="1541" src="https://private-user-images.githubusercontent.com/12505317/307730388-4d39755e-6005-4b43-a6d7-ac8f6e28ba41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjgwNzYsIm5iZiI6MTcwOTAyNzc3NiwicGF0aCI6Ii8xMjUwNTMxNy8zMDc3MzAzODgtNGQzOTc1NWUtNjAwNS00YjQzLWE2ZDctYWM4ZjZlMjhiYTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzA2YjEzN2ZiNGY4OGU4YjhjMDViZTI2MDMwNWM0ZTA0YjEzNTk4MmE1ZjhhYjgwZmVjYmU2YzM1NTc4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UvuBgYWeMephEsCOmwLTnO4VD3QOiwcmbc0lgIRLsiE">
> 
> 要设置一个限定的高度。可以设置给virt list的父容器，也可以直接设置给virt list

是否解决你的问题？

**Comment by JQHee** [comment]
scrollIntoView滚动到指定位置有时候不太对
```
<template>
	<view class="content">
		<view class="buttons-wrapper">
			<view class="to-bottom" @click="toBottomClick">底部</view>
			<view class="to-position" @click="toPositionClick">定位</view>
		</view>
		<view class="virtList-content">
			<VirtList
				class="virtList"
				ref="virtListRef"
				:buffer="2"
				itemKey="id"
				:list="items"
				:minSize="20"
				@toTop="onToTop"
				@toBottom="onToBottom"
				@itemResize="onItemResize"
				@scroll="onScroll"
			>
				<template #default="{ itemData, index }">
					<view class="virt-item" :data-index="index">
						<view v-if="itemData.type === 0">{{ index }} - {{ itemData.text }}</view>
						<image v-if="itemData.type === 1" :src="itemData.text" />
					</view>
				</template>
				<template #header v-if="isShowLoading">
					<view style="width: 100%; height: 20px; display: flex; justify-content: center; align-items: center; background-color: chocolate">loading...</view>
				</template>
			</VirtList>
		</view>
	</view>
</template>

<script>
import { VirtList } from 'vue-virt-list';
// 这个稍
export default {
	components: { VirtList },
	data() {
		return {
			items: [],
			isShowLoading: false,
			lastIndex: null
		};
	},
	onLoad() {
		this.virtListRef = this.$refs.virtListRef;
		for (let i = 0; i < 1000; i++) {
			const item = { text: '', id: i, type: 0 };
			item.text = '测试内容';
			if (i % 2 === 0) {
				item.text = '测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容';
			} else if (i % 5 === 0) {
				item.type = 1;
				item.text = 'https://newfile.ofweek.net/fileremote/msg/chat/2023-04/20230419175448321_dl.png';
			}
			this.items.push(item);
		}
		this.$nextTick(() => {
			this.$refs.virtListRef.scrollToBottom();
		});
	},
	methods: {
		async onToTop() {
			console.log('onToTop');
			if (this.isShowLoading) return;
			this.isShowLoading = true;
		},
		async onToBottom() {
			console.log('onToBottom');
		},
		async onItemResize() {},
		async onScroll(event) {
			//console.log(event);
			const chatListWrapperDom = document.querySelector('.virtList-content');
			const offsetY = this.$refs.virtListRef && this.$refs.virtListRef.getOffset();
			const targetOffsetY = Math.abs(offsetY) + chatListWrapperDom.clientHeight;

			console.log(targetOffsetY);
			let list = document.querySelectorAll('.virt-item'); // 查找所有view元素
			for (let i = 0; i < list.length; i++) {
				const item = list[i];
				//debugger;
				if (targetOffsetY >= item.offsetTop && targetOffsetY <= item.offsetTop + item.clientHeight) {
					// 取出id
					if (this.lastIndex === item.dataset.index) {
						return;
					}
					this.lastIndex = item.dataset.index;
					console.log('目标元素 item.dataset.index', item.dataset.index);
					console.log('目标元素 item.dataset.offsetTop', item.offsetTop);
					console.log('目标元素 item.dataset.maxOffsetY', item.offsetTop + item.clientHeight);
					break;
				}
			}
		},
		toBottomClick() {
			this.$refs.virtListRef?.scrollToBottom();
		},
		toPositionClick() {
			let timeout = setTimeout(() => {
				this.$refs.virtListRef?.scrollIntoView(50);
				clearTimeout(timeout);
				timeout = null;
			}, 20);
		}
	}
};
</script>

<style lang="scss" scoped>
.content {
	width: 100%;
	height: 100%;
	display: flex;
	flex-direction: column;
	.buttons-wrapper {
		display: flex;
		flex-direction: row;
		height: 8vmin;
	}
	.virtList-content {
		width: 100%;
		height: calc(100vmin - 11.73vmin - 8vmin);
	}
}
</style>

```

**Comment by JQHee** [comment]
首次滚动到底部后，再定位到指定50位置时，不正确
<img width="826" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/cbeda3cc-323a-41f1-9335-19ce0f700d37">

**Comment by JQHee** [comment]
buffer 设置了数量，也不是固定的

**Comment by JQHee** [comment]
滑动到底部也没有日志打印

**Comment by keno-lee** [comment]
> buffer 设置了数量，也不是固定的

buffer的确不是固定数量，当没有必要的时候，会不渲染buffer

**Comment by keno-lee** [comment]
> 滑动到底部也没有日志打印

好的。今天晚上空了，针对你的问题都看一下。

**Comment by keno-lee** [comment]
> toBottomClick

<img width="557" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/35287326/b6de072d-dfe3-4910-b9e6-8df010567680">
这是使用问题。不需要使用定时器

**Comment by keno-lee** [comment]
> 滑动到底部也没有日志打印

我在chrome中手机模式中测试是有的。是否跟uniapp有关？

**Comment by keno-lee** [comment]
> 首次滚动到底部后，再定位到指定50位置时，不正确 <img alt="image" width="826" src="https://private-user-images.githubusercontent.com/12505317/308129414-cbeda3cc-323a-41f1-9335-19ce0f700d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjA1MTYsIm5iZiI6MTcwOTEyMDIxNiwicGF0aCI6Ii8xMjUwNTMxNy8zMDgxMjk0MTQtY2JlZGEzY2MtMzIzYS00MWYxLTkzMzUtMTljZTBmNzAwZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmFlNWQ5ZmQ3MWY4Y2U5OWQ3Nzk1NDVjZDhjMTI0ZDhjZmY3NzI0ZjIzMzE5MjQyMzU3MzVlYjdmZjlhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXxRwaokK5qSvDNGIIyNCGnWZhvpqO5jLWn4YTImArc">

确实存在问题。修复中，今天会发版

**Comment by keno-lee** [comment]
> scrollIntoView滚动到指定位置有时候不太对
> 
> ```
> <template>
> 	<view class="content">
> 		<view class="buttons-wrapper">
> 			<view class="to-bottom" @click="toBottomClick">底部</view>
> 			<view class="to-position" @click="toPositionClick">定位</view>
> 		</view>
> 		<view class="virtList-content">
> 			<VirtList
> 				class="virtList"
> 				ref="virtListRef"
> 				:buffer="2"
> 				itemKey="id"
> 				:list="items"
> 				:minSize="20"
> 				@toTop="onToTop"
> 				@toBottom="onToBottom"
> 				@itemResize="onItemResize"
> 				@scroll="onScroll"
> 			>
> 				<template #default="{ itemData, index }">
> 					<view class="virt-item" :data-index="index">
> 						<view v-if="itemData.type === 0">{{ index }} - {{ itemData.text }}</view>
> 						<image v-if="itemData.type === 1" :src="itemData.text" />
> 					</view>
> 				</template>
> 				<template #header v-if="isShowLoading">
> 					<view style="width: 100%; height: 20px; display: flex; justify-content: center; align-items: center; background-color: chocolate">loading...</view>
> 				</template>
> 			</VirtList>
> 		</view>
> 	</view>
> </template>
> 
> <script>
> import { VirtList } from 'vue-virt-list';
> // 这个稍
> export default {
> 	components: { VirtList },
> 	data() {
> 		return {
> 			items: [],
> 			isShowLoading: false,
> 			lastIndex: null
> 		};
> 	},
> 	onLoad() {
> 		this.virtListRef = this.$refs.virtListRef;
> 		for (let i = 0; i < 1000; i++) {
> 			const item = { text: '', id: i, type: 0 };
> 			item.text = '测试内容';
> 			if (i % 2 === 0) {
> 				item.text = '测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容';
> 			} else if (i % 5 === 0) {
> 				item.type = 1;
> 				item.text = 'https://newfile.ofweek.net/fileremote/msg/chat/2023-04/20230419175448321_dl.png';
> 			}
> 			this.items.push(item);
> 		}
> 		this.$nextTick(() => {
> 			this.$refs.virtListRef.scrollToBottom();
> 		});
> 	},
> 	methods: {
> 		async onToTop() {
> 			console.log('onToTop');
> 			if (this.isShowLoading) return;
> 			this.isShowLoading = true;
> 		},
> 		async onToBottom() {
> 			console.log('onToBottom');
> 		},
> 		async onItemResize() {},
> 		async onScroll(event) {
> 			//console.log(event);
> 			const chatListWrapperDom = document.querySelector('.virtList-content');
> 			const offsetY = this.$refs.virtListRef && this.$refs.virtListRef.getOffset();
> 			const targetOffsetY = Math.abs(offsetY) + chatListWrapperDom.clientHeight;
> 
> 			console.log(targetOffsetY);
> 			let list = document.querySelectorAll('.virt-item'); // 查找所有view元素
> 			for (let i = 0; i < list.length; i++) {
> 				const item = list[i];
> 				//debugger;
> 				if (targetOffsetY >= item.offsetTop && targetOffsetY <= item.offsetTop + item.clientHeight) {
> 					// 取出id
> 					if (this.lastIndex === item.dataset.index) {
> 						return;
> 					}
> 					this.lastIndex = item.dataset.index;
> 					console.log('目标元素 item.dataset.index', item.dataset.index);
> 					console.log('目标元素 item.dataset.offsetTop', item.offsetTop);
> 					console.log('目标元素 item.dataset.maxOffsetY', item.offsetTop + item.clientHeight);
> 					break;
> 				}
> 			}
> 		},
> 		toBottomClick() {
> 			this.$refs.virtListRef?.scrollToBottom();
> 		},
> 		toPositionClick() {
> 			let timeout = setTimeout(() => {
> 				this.$refs.virtListRef?.scrollIntoView(50);
> 				clearTimeout(timeout);
> 				timeout = null;
> 			}, 20);
> 		}
> 	}
> };
> </script>
> 
> <style lang="scss" scoped>
> .content {
> 	width: 100%;
> 	height: 100%;
> 	display: flex;
> 	flex-direction: column;
> 	.buttons-wrapper {
> 		display: flex;
> 		flex-direction: row;
> 		height: 8vmin;
> 	}
> 	.virtList-content {
> 		width: 100%;
> 		height: calc(100vmin - 11.73vmin - 8vmin);
> 	}
> }
> </style>
> ```

代码中我看在滚动中在获取当前index，其实可以通过内部的reaciveData中的renderBeigin获取

**Comment by JQHee** [comment]
调试窗口变大变小，滚动到顶部有时候有，有时候没有滚动到底部日志打印
<img width="588" alt="image" src="https://github.com/keno-lee/vue-virt-list/assets/12505317/4d61a470-026f-463c-8760-e498ad5430d9">

**Comment by JQHee** [comment]
> > scrollIntoView滚动到指定位置有时候不太对
> > ```
> > <template>
> > 	<view class="content">
> > 		<view class="buttons-wrapper">
> > 			<view class="to-bottom" @click="toBottomClick">底部</view>
> > 			<view class="to-position" @click="toPositionClick">定位</view>
> > 		</view>
> > 		<view class="virtList-content">
> > 			<VirtList
> > 				class="virtList"
> > 				ref="virtListRef"
> > 				:buffer="2"
> > 				itemKey="id"
> > 				:list="items"
> > 				:minSize="20"
> > 				@toTop="onToTop"
> > 				@toBottom="onToBottom"
> > 				@itemResize="onItemResize"
> > 				@scroll="onScroll"
> > 			>
> > 				<template #default="{ itemData, index }">
> > 					<view class="virt-item" :data-index="index">
> > 						<view v-if="itemData.type === 0">{{ index }} - {{ itemData.text }}</view>
> > 						<image v-if="itemData.type === 1" :src="itemData.text" />
> > 					</view>
> > 				</template>
> > 				<template #header v-if="isShowLoading">
> > 					<view style="width: 100%; height: 20px; display: flex; justify-content: center; align-items: center; background-color: chocolate">loading...</view>
> > 				</template>
> > 			</VirtList>
> > 		</view>
> > 	</view>
> > </template>
> > 
> > <script>
> > import { VirtList } from 'vue-virt-list';
> > // 这个稍
> > export default {
> > 	components: { VirtList },
> > 	data() {
> > 		return {
> > 			items: [],
> > 			isShowLoading: false,
> > 			lastIndex: null
> > 		};
> > 	},
> > 	onLoad() {
> > 		this.virtListRef = this.$refs.virtListRef;
> > 		for (let i = 0; i < 1000; i++) {
> > 			const item = { text: '', id: i, type: 0 };
> > 			item.text = '测试内容';
> > 			if (i % 2 === 0) {
> > 				item.text = '测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容';
> > 			} else if (i % 5 === 0) {
> > 				item.type = 1;
> > 				item.text = 'https://newfile.ofweek.net/fileremote/msg/chat/2023-04/20230419175448321_dl.png';
> > 			}
> > 			this.items.push(item);
> > 		}
> > 		this.$nextTick(() => {
> > 			this.$refs.virtListRef.scrollToBottom();
> > 		});
> > 	},
> > 	methods: {
> > 		async onToTop() {
> > 			console.log('onToTop');
> > 			if (this.isShowLoading) return;
> > 			this.isShowLoading = true;
> > 		},
> > 		async onToBottom() {
> > 			console.log('onToBottom');
> > 		},
> > 		async onItemResize() {},
> > 		async onScroll(event) {
> > 			//console.log(event);
> > 			const chatListWrapperDom = document.querySelector('.virtList-content');
> > 			const offsetY = this.$refs.virtListRef && this.$refs.virtListRef.getOffset();
> > 			const targetOffsetY = Math.abs(offsetY) + chatListWrapperDom.clientHeight;
> > 
> > 			console.log(targetOffsetY);
> > 			let list = document.querySelectorAll('.virt-item'); // 查找所有view元素
> > 			for (let i = 0; i < list.length; i++) {
> > 				const item = list[i];
> > 				//debugger;
> > 				if (targetOffsetY >= item.offsetTop && targetOffsetY <= item.offsetTop + item.clientHeight) {
> > 					// 取出id
> > 					if (this.lastIndex === item.dataset.index) {
> > 						return;
> > 					}
> > 					this.lastIndex = item.dataset.index;
> > 					console.log('目标元素 item.dataset.index', item.dataset.index);
> > 					console.log('目标元素 item.dataset.offsetTop', item.offsetTop);
> > 					console.log('目标元素 item.dataset.maxOffsetY', item.offsetTop + item.clientHeight);
> > 					break;
> > 				}
> > 			}
> > 		},
> > 		toBottomClick() {
> > 			this.$refs.virtListRef?.scrollToBottom();
> > 		},
> > 		toPositionClick() {
> > 			let timeout = setTimeout(() => {
> > 				this.$refs.virtListRef?.scrollIntoView(50);
> > 				clearTimeout(timeout);
> > 				timeout = null;
> > 			}, 20);
> > 		}
> > 	}
> > };
> > </script>
> > 
> > <style lang="scss" scoped>
> > .content {
> > 	width: 100%;
> > 	height: 100%;
> > 	display: flex;
> > 	flex-direction: column;
> > 	.buttons-wrapper {
> > 		display: flex;
> > 		flex-direction: row;
> > 		height: 8vmin;
> > 	}
> > 	.virtList-content {
> > 		width: 100%;
> > 		height: calc(100vmin - 11.73vmin - 8vmin);
> > 	}
> > }
> > </style>
> > ```
> 
> 代码中我看在滚动中在获取当前index，其实可以通过内部的reaciveData中的renderBeigin获取

reaciveData中的renderBeigin，在代码中没见有有啊，这个要怎么获取

**Comment by JQHee** [comment]
> > > 首次滚动到底部后，再定位到指定50位置时，不正确 <img alt="image" width="826" src="https://private-user-images.githubusercontent.com/12505317/308129414-cbeda3cc-323a-41f1-9335-19ce0f700d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjA1MTYsIm5iZiI6MTcwOTEyMDIxNiwicGF0aCI6Ii8xMjUwNTMxNy8zMDgxMjk0MTQtY2JlZGEzY2MtMzIzYS00MWYxLTkzMzUtMTljZTBmNzAwZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmFlNWQ5ZmQ3MWY4Y2U5OWQ3Nzk1NDVjZDhjMTI0ZDhjZmY3NzI0ZjIzMzE5MjQyMzU3MzVlYjdmZjlhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXxRwaokK5qSvDNGIIyNCGnWZhvpqO5jLWn4YTImArc">
> > 
> > 
> > 确实存在问题。修复中，今天会发版
> 
> v1.0.5已解决该问题。pr内容：#8


https://github.com/keno-lee/vue-virt-list/assets/12505317/2c4322d8-61c5-4a8e-aae8-533012f1459d

更新到最新版本了，滚动到指定位置还是有问题

**Comment by JQHee** [comment]
> > > 首次滚动到底部后，再定位到指定50位置时，不正确 <img alt="image" width="826" src="https://private-user-images.githubusercontent.com/12505317/308129414-cbeda3cc-323a-41f1-9335-19ce0f700d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjA1MTYsIm5iZiI6MTcwOTEyMDIxNiwicGF0aCI6Ii8xMjUwNTMxNy8zMDgxMjk0MTQtY2JlZGEzY2MtMzIzYS00MWYxLTkzMzUtMTljZTBmNzAwZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmFlNWQ5ZmQ3MWY4Y2U5OWQ3Nzk1NDVjZDhjMTI0ZDhjZmY3NzI0ZjIzMzE5MjQyMzU3MzVlYjdmZjlhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXxRwaokK5qSvDNGIIyNCGnWZhvpqO5jLWn4YTImArc">
> > 
> > 
> > 确实存在问题。修复中，今天会发版
> 
> v1.0.5已解决该问题。pr内容：#8


https://github.com/keno-lee/vue-virt-list/assets/12505317/2c4322d8-61c5-4a8e-aae8-533012f1459d

更新到最新版本了，滚动到指定位置还是有问题

**Comment by keno-lee** [comment]
> 代码中我看在滚动中在获取当前index，其实可以通过内部的reaciveData中的renderBeigin获取

加我微信吧。leemax123456

**Comment by keno-lee** [comment]
> > > scrollIntoView滚动到指定位置有时候不太对
> > > ```
> > > <template>
> > > 	<view class="content">
> > > 		<view class="buttons-wrapper">
> > > 			<view class="to-bottom" @click="toBottomClick">底部</view>
> > > 			<view class="to-position" @click="toPositionClick">定位</view>
> > > 		</view>
> > > 		<view class="virtList-content">
> > > 			<VirtList
> > > 				class="virtList"
> > > 				ref="virtListRef"
> > > 				:buffer="2"
> > > 				itemKey="id"
> > > 				:list="items"
> > > 				:minSize="20"
> > > 				@toTop="onToTop"
> > > 				@toBottom="onToBottom"
> > > 				@itemResize="onItemResize"
> > > 				@scroll="onScroll"
> > > 			>
> > > 				<template #default="{ itemData, index }">
> > > 					<view class="virt-item" :data-index="index">
> > > 						<view v-if="itemData.type === 0">{{ index }} - {{ itemData.text }}</view>
> > > 						<image v-if="itemData.type === 1" :src="itemData.text" />
> > > 					</view>
> > > 				</template>
> > > 				<template #header v-if="isShowLoading">
> > > 					<view style="width: 100%; height: 20px; display: flex; justify-content: center; align-items: center; background-color: chocolate">loading...</view>
> > > 				</template>
> > > 			</VirtList>
> > > 		</view>
> > > 	</view>
> > > </template>
> > > 
> > > <script>
> > > import { VirtList } from 'vue-virt-list';
> > > // 这个稍
> > > export default {
> > > 	components: { VirtList },
> > > 	data() {
> > > 		return {
> > > 			items: [],
> > > 			isShowLoading: false,
> > > 			lastIndex: null
> > > 		};
> > > 	},
> > > 	onLoad() {
> > > 		this.virtListRef = this.$refs.virtListRef;
> > > 		for (let i = 0; i < 1000; i++) {
> > > 			const item = { text: '', id: i, type: 0 };
> > > 			item.text = '测试内容';
> > > 			if (i % 2 === 0) {
> > > 				item.text = '测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容';
> > > 			} else if (i % 5 === 0) {
> > > 				item.type = 1;
> > > 				item.text = 'https://newfile.ofweek.net/fileremote/msg/chat/2023-04/20230419175448321_dl.png';
> > > 			}
> > > 			this.items.push(item);
> > > 		}
> > > 		this.$nextTick(() => {
> > > 			this.$refs.virtListRef.scrollToBottom();
> > > 		});
> > > 	},
> > > 	methods: {
> > > 		async onToTop() {
> > > 			console.log('onToTop');
> > > 			if (this.isShowLoading) return;
> > > 			this.isShowLoading = true;
> > > 		},
> > > 		async onToBottom() {
> > > 			console.log('onToBottom');
> > > 		},
> > > 		async onItemResize() {},
> > > 		async onScroll(event) {
> > > 			//console.log(event);
> > > 			const chatListWrapperDom = document.querySelector('.virtList-content');
> > > 			const offsetY = this.$refs.virtListRef && this.$refs.virtListRef.getOffset();
> > > 			const targetOffsetY = Math.abs(offsetY) + chatListWrapperDom.clientHeight;
> > > 
> > > 			console.log(targetOffsetY);
> > > 			let list = document.querySelectorAll('.virt-item'); // 查找所有view元素
> > > 			for (let i = 0; i < list.length; i++) {
> > > 				const item = list[i];
> > > 				//debugger;
> > > 				if (targetOffsetY >= item.offsetTop && targetOffsetY <= item.offsetTop + item.clientHeight) {
> > > 					// 取出id
> > > 					if (this.lastIndex === item.dataset.index) {
> > > 						return;
> > > 					}
> > > 					this.lastIndex = item.dataset.index;
> > > 					console.log('目标元素 item.dataset.index', item.dataset.index);
> > > 					console.log('目标元素 item.dataset.offsetTop', item.offsetTop);
> > > 					console.log('目标元素 item.dataset.maxOffsetY', item.offsetTop + item.clientHeight);
> > > 					break;
> > > 				}
> > > 			}
> > > 		},
> > > 		toBottomClick() {
> > > 			this.$refs.virtListRef?.scrollToBottom();
> > > 		},
> > > 		toPositionClick() {
> > > 			let timeout = setTimeout(() => {
> > > 				this.$refs.virtListRef?.scrollIntoView(50);
> > > 				clearTimeout(timeout);
> > > 				timeout = null;
> > > 			}, 20);
> > > 		}
> > > 	}
> > > };
> > > </script>
> > > 
> > > <style lang="scss" scoped>
> > > .content {
> > > 	width: 100%;
> > > 	height: 100%;
> > > 	display: flex;
> > > 	flex-direction: column;
> > > 	.buttons-wrapper {
> > > 		display: flex;
> > > 		flex-direction: row;
> > > 		height: 8vmin;
> > > 	}
> > > 	.virtList-content {
> > > 		width: 100%;
> > > 		height: calc(100vmin - 11.73vmin - 8vmin);
> > > 	}
> > > }
> > > </style>
> > > ```
> > 
> > 
> > 代码中我看在滚动中在获取当前index，其实可以通过内部的reaciveData中的renderBeigin获取
> 
> 主要是获取刚刚出现在顶部dom,绑定在data-上的id

直接获取 this.$refs.virtListRef.reactiveData.inViewBegin，然后直接在元数据中拿到 list[this.$refs.virtListRef.reactiveData.inViewBegin]中你要的那个id，本身data-id就是源数据提供的
