### ISSUE TITLE
当list 数据更新，然后item的高度会发生变化，现在是需要手动滚一下才能显示出来，变化的item的布局

### ISSUE THREAD

**Issue by yhyeye** [keno-lee/vue-virt-list#9]

**Comment by keno-lee** [comment]
> 
如果你的数据在一万条左右，直接将你的数据改用响应式包装起来，即可。
如果你的数据在几十万，建议使用非响应式数据来保证性能，然后手动设置key来解决响应式。后面我会写一个demo。
https://keno-lee.github.io/vue-virt-list/guide/instructions/
